/* My Family Roots — Photo & Gallery foundation (Stage 1.1) */
(()=>{
  if(window.__MFR_PHOTO_GALLERY_LOADED)return;
  window.__MFR_PHOTO_GALLERY_LOADED=true;
  document.addEventListener('DOMContentLoaded',()=>{
    const LS='mfr_photo_gallery_v1',DB='mfr_photo_gallery_db',STORE='photos';
    let photos=[];
    const members=()=>window.FAMILY_MEMBERS_STATIC||[];
    const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
    const nameOf=id=>{const x=members().find(p=>String(p[0]).toLowerCase()===String(id).toLowerCase());return x?.[1]||'Unnamed'};
    let dbp;
    const db=()=>dbp||(dbp=new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id',autoIncrement:true});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)}));
    const allDB=()=>db().then(d=>new Promise((res,rej)=>{const q=d.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)}));
    const putDB=x=>db().then(d=>new Promise((res,rej)=>{const q=d.transaction(STORE,'readwrite').objectStore(STORE).add(x);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)}));
    const delDB=id=>db().then(d=>new Promise((res,rej)=>{const q=d.transaction(STORE,'readwrite').objectStore(STORE).delete(id);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)}));
    const readLegacy=()=>{try{return JSON.parse(localStorage.getItem(LS)||'[]')||[]}catch{return[]}};
    const compress=f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));c.getContext('2d').drawImage(im,0,0,c.width,c.height);c.toBlob(b=>b?resolve(b):reject(new Error('Image conversion failed')),'image/jpeg',.86)};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(f)});
    const load=async()=>{try{photos=await allDB();if(!photos.length){const old=readLegacy();for(const p of old){try{const blob=await (await fetch(p.data)).blob();await putDB({member:p.member,caption:p.caption,date:p.date,blob})}catch{}}if(old.length)localStorage.removeItem(LS);photos=await allDB()}}catch{photos=readLegacy().map((p,i)=>({...p,id:'legacy-'+i}))}};
    const open=async()=>{
      let old=document.getElementById('mfrGalleryOverlay');if(old)old.remove();
      const o=document.createElement('div');o.id='mfrGalleryOverlay';o.style='position:fixed;inset:0;background:#24170bcc;z-index:100;overflow:auto;padding:12px';
      const opts=members().map(p=>'<option value="'+esc(p[0])+'">'+esc(p[1]||'Unnamed')+' ['+esc(p[0])+']</option>').join('');
      o.innerHTML='<div style="max-width:900px;margin:auto;background:#fffdf9;border:1px solid #dfd2bf;border-radius:18px;padding:16px"><div style="display:flex;align-items:center;gap:8px"><h2 style="margin:0">📷 Family Photos & Gallery</h2><button id="mfrClose" style="margin-left:auto;padding:9px 12px;border-radius:10px;border:1px solid #dfd2bf;background:#fff">✕ Close</button></div><p style="color:#756a5e;font-size:13px">Stage 1: photos stay on this device. Mobile photo selection is supported; shared cloud gallery will come with database sync later.</p><label>Family member</label><select id="mfrPhotoMember" style="width:100%;padding:10px;border:1px solid #dfd2bf;border-radius:10px">'+opts+'</select><label>Caption</label><input id="mfrPhotoCaption" placeholder="e.g. Wedding day" style="width:100%;padding:10px;border:1px solid #dfd2bf;border-radius:10px"><label>Date</label><input id="mfrPhotoDate" type="date" style="width:100%;padding:10px;border:1px solid #dfd2bf;border-radius:10px"><label>Photo</label><button id="mfrChoosePhoto" style="width:100%;padding:13px;border-radius:10px;border:1px solid #dfd2bf;background:#fff;font:inherit;text-align:left">📱 Choose from Photos / Gallery</button><input id="mfrPhotoFile" type="file" accept="image/*" multiple style="display:none"><div id="mfrPhotoHint" style="margin-top:7px;color:#756a5e;font-size:12px">Tap the button above and select one or more family photos.</div><div id="mfrPhotoGrid" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:10px;margin-top:16px"></div></div>';
      document.body.appendChild(o);
      document.getElementById('mfrClose').onclick=()=>o.remove();
      document.getElementById('mfrChoosePhoto').onclick=()=>document.getElementById('mfrPhotoFile').click();
      const render=()=>{const g=document.getElementById('mfrPhotoGrid');g.innerHTML=photos.length?photos.map((p,i)=>{const src=p.blob?URL.createObjectURL(p.blob):p.data;return '<div style="background:#fff;border:1px solid #dfd2bf;border-radius:14px;padding:8px"><img src="'+src+'" style="width:100%;aspect-ratio:1;object-fit:cover;border-radius:10px"><b>'+esc(nameOf(p.member))+'</b><div style="font-size:12px;color:#756a5e">'+esc(p.caption||'')+(p.date?' · '+esc(p.date):'')+'</div><button data-i="'+i+'" style="margin-top:6px;padding:6px 9px;border-radius:8px;border:1px solid #dfd2bf;background:#fff">Delete</button></div>'}).join(''):'<div style="color:#756a5e">No photos yet. Add the first family photo above.</div>';g.querySelectorAll('button[data-i]').forEach(b=>b.onclick=async()=>{const p=photos[Number(b.dataset.i)];if(p?.id&&typeof p.id==='number')await delDB(p.id);photos.splice(Number(b.dataset.i),1);render()})};
      document.getElementById('mfrPhotoFile').onchange=async e=>{const fs=[...e.target.files||[]];if(!fs.length)return;const member=document.getElementById('mfrPhotoMember').value,caption=document.getElementById('mfrPhotoCaption').value.trim(),date=document.getElementById('mfrPhotoDate').value,h=document.getElementById('mfrPhotoHint');h.textContent='⏳ Adding '+fs.length+' photo'+(fs.length>1?'s':'')+'…';try{for(const f of fs){if(!f.type.startsWith('image/'))continue;const blob=await compress(f),id=await putDB({member,caption,date,blob});photos.unshift({id,member,caption,date,blob})}h.textContent='✅ Photo added. You can add more.';render();document.getElementById('mfrPhotoCaption').value='';document.getElementById('mfrPhotoDate').value=''}catch(err){alert('Could not save the photo on this device. Please try one photo first.');h.textContent='⚠️ Photo could not be saved.'}e.target.value=''};
      await load();render();
    };
    const b=document.createElement('button');b.className='btn';b.textContent='📷 Photos & Gallery';b.onclick=open;document.querySelector('.bar')?.appendChild(b);
  });
})();